title: Comunicaciones de Datos
description: Repositorio con contenido teórico y práctico.
show_downloads: true
comments: false
logo_url: https://elblogdemaripozo.files.wordpress.com/2011/03/red-de-datos.jpg
google_analytics:
git_branch: gh-pages
theme: 
use_github_wiki: false
use_prose_io: true
google_cse_token: 007197903287787072094:8rbvkeqo6qw
custom_sidebar: true
gems:
  - jekyll-sitemap
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-feed
